### ISSUE TITLE
Review of distance function

### ISSUE THREAD

**Issue by aylapear** [UBC-MDS/KMediansPy#11]
Looks great, here are a few minor suggestions

- in the doc string under parameters there is a small x while the input is X, this could be consistent. 
- in the kmedians and the summary function small x was used,  change the distance function to be consistent with this notation
- add some comments in the code above n, k and the loops 
- change the variable name dist to distance

**Comment by aylapear** [comment]
I noticed when trying to integrate the distance function it was missing importing numpy

**Comment by sreyaguha** [comment]
Changes made to the distance() function
