### ISSUE TITLE
Review of Kmedians function

### ISSUE THREAD

**Issue by aylapear** [UBC-MDS/KMediansPy#12]
- in the doc string there are large X's but the input small so change this to be consistent (i think we should go with small x, that seems more common in notation)
- add some comments in the code for the variables and the loops
- change dist to distance
- once we get the package working we need to switch out the distance function to ours

**Comment by aylapear** [comment]
I will accept the pull request and start working on making the functions into a working package so we can integrate our distance function into kmedians and summary function

**Comment by aylapear** [comment]
- [x] change the file name as it doesn't seem like we can import something that has a dash in the file name

**Comment by sreyaguha** [comment]
Changes made to the KMedians function
